# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_ind', models.BooleanField()),
                ('roster_status', models.CharField(max_length=1, null=True)),
                ('date_assigned', models.DateField()),
                ('years', models.IntegerField(default=0)),
                ('years_remaining', models.IntegerField(null=True)),
                ('date_terminated', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('q', 'QB'), ('r', 'RB'), ('w', 'WR'), ('t', 'TE'), ('k', 'PK'), ('d', 'DEF')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('week_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('run_status', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contracts.Franchise'),
        ),
        migrations.AddField(
            model_name='contract',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='contracts.Player'),
        ),
    ]
