# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='franchise_id',
            new_name='franchise',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='player_id',
            new_name='player',
        ),
    ]
