# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20170919_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='contract_id',
            new_name='id',
        ),
    ]
