# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20170919_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise_fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchup_type', models.CharField(choices=[('p', 'Playoffs'), ('r', 'Regular Season'), ('b', 'Bye')], max_length=1)),
                ('result', models.CharField(blank=True, choices=[('w', 'Win'), ('l', 'Loss'), ('t', 'Tie')], max_length=1)),
                ('total_score', models.FloatField()),
                ('opponent_score', models.FloatField()),
                ('franchise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Franchise')),
                ('opponent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Franchise', to='contracts.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='Player_fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_status', models.CharField(max_length=50)),
                ('actual_status', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('franchise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Franchise')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('week_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('run_status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='player_fact',
            name='week_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Week'),
        ),
        migrations.AddField(
            model_name='franchise_fact',
            name='week_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Week'),
        ),
    ]
