# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20171017_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchise_fact',
            old_name='franchise_id',
            new_name='franchise',
        ),
        migrations.RenameField(
            model_name='franchise_fact',
            old_name='opponent_id',
            new_name='opponent',
        ),
        migrations.RenameField(
            model_name='franchise_fact',
            old_name='week_id',
            new_name='week',
        ),
        migrations.RenameField(
            model_name='player_fact',
            old_name='franchise_id',
            new_name='franchise',
        ),
        migrations.RenameField(
            model_name='player_fact',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='player_fact',
            old_name='week_id',
            new_name='week',
        ),
    ]
