# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_auto_20171017_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_fact',
            name='actual_status',
        ),
        migrations.AlterField(
            model_name='player_fact',
            name='roster_status',
            field=models.CharField(choices=[('s', 'Starter'), ('b', 'Bench'), ('i', 'IR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='player_fact',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
