# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_auto_20171018_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise_fact',
            name='opponent_score',
            field=models.FloatField(null=True),
        ),
    ]
