# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_auto_20171018_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise_fact',
            name='result',
            field=models.CharField(choices=[('w', 'Win'), ('l', 'Loss'), ('t', 'Tie')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player_fact',
            name='roster_status',
            field=models.CharField(choices=[('s', 'Starter'), ('b', 'Bench'), ('i', 'IR'), ('f', 'Free Agent')], max_length=50),
        ),
    ]
