# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_auto_20171018_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='run_date',
            field=models.DateField(null=True),
        ),
    ]
