# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_week_run_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='run_date',
        ),
    ]
