# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_auto_20171101_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='current_years',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
