# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_auto_20171101_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='current_years',
            field=models.IntegerField(null=True),
        ),
    ]
