# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_auto_20171101_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='current_years',
        ),
    ]
