# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_remove_contract_current_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='years_remaining',
            field=models.IntegerField(null=True),
        ),
    ]
