# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_contract_years_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='roster_status',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
