# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-09 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='franchise_fact',
            unique_together=set([('franchise', 'week')]),
        ),
    ]
