# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-30 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('history', '0002_auto_20181008_2052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player_fact',
            unique_together=set([('player', 'franchise', 'week')]),
        ),
    ]
